spring.application.name=Vendura Backend
spring.profiles.active=secret

sentry.dsn=https://3cf0589420f7a33cdd8ee0b64154a087@o4508913879285760.ingest.de.sentry.io/4508913895604304
# Add data like request headers and IP for users,
# see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
sentry.send-default-pii=true
# Set traces-sample-rate to 1.0 to capture 100% of transactions for tracing.
# We recommend adjusting this value in production.
sentry.traces-sample-rate=1.0